name: Improve Pathway
description: Suggest improvements to an existing pathway model
title: "[Improve Pathway]: "
labels: ["needs work"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know about pathways in need of improvement! Make sure to include the pathway name and WPID in the title above.
  - type: input
    id: pathway-url
    attributes:
      label: Pathway URL
      description: Add a link to the pathway that is in need of improvement.
      placeholder: https://classic.wikipathways.org/index.php/Pathway:WP615
    validations:
      required: true
  - type: textarea
    id: curation-tasks
    attributes:
      label: Suggested imoprovements
      description: What are the specific things that need to be improved?
      placeholder: List of things to do
      value: "The pathway is missing database identifiers and interactions!"
    validations:
      required: true
