name: New Pathway
description: Suggest a new pathway model
title: "[New Pathway]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know of new potential pathway models! Make sure to add the suggested pathway title or topic in the title above.
  - type: input
    id: pathway-title
    attributes:
      label: Suggested pathway title
      description: Suggest a title for the new pathway model. If the pathway is from a published paper figure, the title could be a variation of the figure caption.
      placeholder: AK-STAT signaling in the regulation of Beta-cells
    validations:
      required: false
  - type: textarea
    id: pathway-source
    attributes:
      label: Pathway Source URL(s)
      description: Add links to published papers, figure or other relevant source (open source)
      placeholder: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6143874/
    validations:
      required: true
  - type: textarea
    id: curation-tasks
    attributes:
      label: Notes
      description: Add any notes relevant to the proposed pathway model
      placeholder: Notes
      value: "This pathway content is not previously covered at WikiPathways....."
    validations:
      required: false
